sudo: false
language: node_js
node_js:
  - '12'
cache:
  directories:
    - ./node_modules
install:
  - npm install
script:
  - ng build
  - npm run scully
  - rm -r -f docs/site
  - mkdir docs/site
  - cp -a dist/static/. docs/site/
